name: Setup and Build dpd Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Specify the version of Node.js you need

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Set up the Python version required by the project

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies with Poetry
      run: |
        poetry install
      shell: /usr/bin/bash -e {0}

    - name: Run initial setup script
      run: poetry run bash scripts/bash/initial_setup_run_once.sh

    - name: Build the database
      run: poetry run bash scripts/bash/build_db.sh

    - name: Zip the database file
      run: zip dpd-db.zip ./dpd.db

    - name: Upload zipped database as artifact
      uses: actions/upload-artifact@v2
      with:
        name: dpd-db
        path: ./dpd-db.zip
